name: "public to maven central"
on:
  push:
    tags:
      - "v*"
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to Maven Central
    steps:
      - name: ğŸ¯checkout code
        uses: actions/checkout@v4
      - name: ğŸ£init java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: ğŸ¦‡Install GPG
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          sudo apt install -y gpg
          sudo echo "$SIGNING_KEY" | gpg --dearmor > ${HOME}/secring.gpg

      - name: ğŸµinit gradle
        uses: gradle/actions/setup-gradle@v4

      - name: ğŸAdd Gradle Properties
        env:
          MAVEN_CENTRAL_USER_NAME: ${{ secrets.MAVEN_CENTRAL_USER_NAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: |
          echo "mavenCentralUsername=${MAVEN_CENTRAL_USER_NAME}" >> gradle.properties
          echo "mavenCentralPassword=${MAVEN_CENTRAL_PASSWORD}" >> gradle.properties
          echo "signing.keyId=${SIGNING_KEY_ID}" >> gradle.properties
          echo "signing.password=${SIGNING_KEY_PASSWORD}" >> gradle.properties
          echo "signing.secretKeyRingFile=${HOME}/secring.gpg" >> gradle.properties

      - name: ğŸ¸publish to maven central
        run: |
          ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
